name: 'Build'
description: 'Builds the repository'
inputs:
  token:
    description: 'token to download artifacts'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies library and prepare dependency folder
      shell: bash
      run: |
        mkdir ../dep
        sudo apt-get update
        sudo apt-get install libeigen3-dev libgtest-dev
        sudo apt-get install redis libhiredis-dev libjsoncpp-dev

    - name: Build Sai-common
      shell: bash
      run: |
        export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:dep/*
        mkdir build && cd build
        cmake .. && make -j8

    - name: Check build status
      shell: bash
      run: |
        cd build
        make --always-make --dry-run