name: 'Build'
description: 'Builds the repository'
inputs:
  token:
    description: 'token to download artifacts'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      uses: manips-sai-org/sai-common/custom_github_actions/dependencies@master

    - name: Setup Sai-urdfreader
      uses: manips-sai-org/sai-common/custom_github_actions/sai-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: sai-urdfreader
        
    - name: Setup Sai-model
      uses: manips-sai-org/sai-common/custom_github_actions/sai-model@master
      with:
        token: ${{ inputs.token }}

    - name: Setup chai3d
      uses: manips-sai-org/sai-common/custom_github_actions/sai-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: chai3d

    - name: Setup Sai-Graphics
      uses: manips-sai-org/sai-common/custom_github_actions/sai-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: sai-graphics

    - name: Setup Sai-Common
      uses: manips-sai-org/sai-common/custom_github_actions/sai-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: sai-common

    - name: Setup Sai-Simulation
      uses: manips-sai-org/sai-common/custom_github_actions/sai-repositories@master
      with:
        token: ${{ inputs.token }}
        repo-name: sai-simulation

    - name: Setup Sai-Primitives
      uses: manips-sai-org/sai-common/custom_github_actions/sai-primitives@master
      with:
        token: ${{ inputs.token }}

    - name: Build Sai-Interfaces
      shell: bash
      run: |
        export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:dep/*
        mkdir build && cd build
        cmake .. && make -j8

    - name: Check build status
      shell: bash
      run: |
        cd build
        make --always-make --dry-run