name: Build master and upload artifact

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: build-repo
        uses: ./.github/actions/build-repo
        with: 
          token: ${{ secrets.SAI_TOKEN }}

      - name: Archive Sai-graphics Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sai-graphics-artifact
          path: build/libsai-graphics.a